package com.shahsurveyors.myapplication.ui.crm

import androidx.compose.foundation.background
import androidx.compose.foundation.layout.*
import androidx.compose.foundation.lazy.LazyColumn
import androidx.compose.foundation.lazy.items
import androidx.compose.foundation.shape.CircleShape
import androidx.compose.foundation.shape.RoundedCornerShape
import androidx.compose.material.icons.Icons
import androidx.compose.material.icons.automirrored.filled.ArrowBack
import androidx.compose.material.icons.filled.*
import androidx.compose.material3.*
import androidx.compose.runtime.*
import androidx.compose.ui.Alignment
import androidx.compose.ui.Modifier
import androidx.compose.ui.text.font.FontWeight
import androidx.compose.ui.unit.dp
import androidx.compose.ui.unit.sp
import com.google.firebase.Timestamp
import com.shahsurveyors.myapplication.models.ClientModel
import com.shahsurveyors.myapplication.models.ClientPaymentRecord
import com.shahsurveyors.myapplication.ui.theme.*
import java.text.SimpleDateFormat
import java.util.Date
import java.util.Locale

@OptIn(ExperimentalMaterial3Api::class)
@Composable
fun CRMClientScreen(viewModel: ClientViewModel, onBack: () -> Unit = {}, onAddClient: () -> Unit = {}) {
    var searchQuery by remember { mutableStateOf("") }
    var menuClient by remember { mutableStateOf<ClientModel?>(null) }
    var paymentClient by remember { mutableStateOf<ClientModel?>(null) }
    var receivableClient by remember { mutableStateOf<ClientModel?>(null) }
    var historyClient by remember { mutableStateOf<ClientModel?>(null) }
    LaunchedEffect(Unit) { viewModel.fetchClients() }
    val filtered = remember(viewModel.clients, searchQuery) { val q=searchQuery.trim(); if(q.isEmpty()) viewModel.clients.toList() else viewModel.clients.filter { it.name.contains(q,true)||it.contactPerson.contains(q,true)||it.email.contains(q,true)||it.phone.contains(q)||it.whatsapp.contains(q)||it.address.contains(q,true)||it.city.contains(q,true)||it.state.contains(q,true) } }
    Scaffold(topBar={TopAppBar(title={Column{Text("Client Directory",fontWeight=FontWeight.Bold,color=ShahWhite);Text("Clients • Receivables • Payments • History",fontSize=10.sp,color=ShahWhite.copy(.72f))}},navigationIcon={IconButton(onClick=onBack){Icon(Icons.AutoMirrored.Filled.ArrowBack,"Back",tint=ShahWhite)}},colors=TopAppBarDefaults.topAppBarColors(containerColor=ShahDarkGreen))},floatingActionButton={FloatingActionButton(onClick=onAddClient,containerColor=ShahGreen,contentColor=ShahWhite,shape=RoundedCornerShape(16.dp)){Icon(Icons.Default.PersonAdd,"Add Client")}},containerColor=ShahGrey){padding->Column(Modifier.fillMaxSize().padding(padding).background(ShahGrey)){OutlinedTextField(searchQuery,{searchQuery=it},Modifier.fillMaxWidth().padding(16.dp),singleLine=true,placeholder={Text("Search client, contact, phone or city")},leadingIcon={Icon(Icons.Default.Search,null,tint=ShahMediumGrey)},shape=RoundedCornerShape(14.dp),colors=OutlinedTextFieldDefaults.colors(focusedBorderColor=ShahGreen,unfocusedBorderColor=ShahLightGrey,focusedContainerColor=ShahWhite,unfocusedContainerColor=ShahWhite));Text("${filtered.size} client${if(filtered.size==1)"" else "s"}",fontWeight=FontWeight.Bold,color=ShahDarkGreen,modifier=Modifier.padding(horizontal=16.dp));if(filtered.isEmpty())Box(Modifier.fillMaxSize(),contentAlignment=Alignment.Center){Text("No clients found",fontWeight=FontWeight.Bold,color=ShahDarkGreen)}else LazyColumn(Modifier.fillMaxSize(),contentPadding=PaddingValues(16.dp,8.dp,16.dp,90.dp)){items(filtered,key={it.id}){client->ClientCard(client){menuClient=client}}}}}
    menuClient?.let { client -> AlertDialog(onDismissRequest={menuClient=null},title={Text(client.name,fontWeight=FontWeight.Bold)},text={Column(verticalArrangement=Arrangement.spacedBy(8.dp)){MenuAction("ADD AMOUNT DUE","Add or increase client receivable",Icons.Default.AddCard){menuClient=null;receivableClient=client};MenuAction("RECORD PAYMENT","Enter money received from client",Icons.Default.Payments){menuClient=null;paymentClient=client};MenuAction("PAYMENT HISTORY","See every payment and running balance",Icons.Default.History){menuClient=null;historyClient=client}}},confirmButton={TextButton(onClick={menuClient=null}){Text("CLOSE")}}) }
    receivableClient?.let{AddReceivableDialog(it,viewModel){receivableClient=null}};paymentClient?.let{RecordPaymentDialog(it,viewModel){paymentClient=null}};historyClient?.let{ClientPaymentHistoryDialog(it,viewModel){historyClient=null}}
}

@Composable private fun MenuAction(title:String,subtitle:String,icon:androidx.compose.ui.graphics.vector.ImageVector,onClick:()->Unit){Card(onClick=onClick,modifier=Modifier.fillMaxWidth(),shape=RoundedCornerShape(12.dp),colors=CardDefaults.cardColors(containerColor=ShahWhite)){Row(Modifier.padding(12.dp),verticalAlignment=Alignment.CenterVertically){Icon(icon,null,tint=ShahGreen,modifier=Modifier.size(25.dp));Spacer(Modifier.width(12.dp));Column{Text(title,fontWeight=FontWeight.Bold);Text(subtitle,fontSize=10.sp,color=ShahMediumGrey)}}}}

@Composable fun ClientCard(client:ClientModel,onMenu:()->Unit){val pending=(client.totalReceivable-client.totalPaid).coerceAtLeast(0.0);val status=when{client.totalReceivable<=0.0->"NO DUE";pending<=0.01->"FULLY PAID";client.totalPaid>0.0->"PARTIAL";else->"PENDING"};Card(Modifier.fillMaxWidth().padding(vertical=6.dp),RoundedCornerShape(18.dp),colors=CardDefaults.cardColors(containerColor=ShahWhite),elevation=CardDefaults.cardElevation(2.dp)){Column(Modifier.padding(16.dp)){Row(verticalAlignment=Alignment.CenterVertically){Surface(Modifier.size(50.dp),shape=CircleShape,color=ShahGreen.copy(.10f)){Box(contentAlignment=Alignment.Center){Text(client.name.take(1).uppercase(),color=ShahGreen,fontWeight=FontWeight.Bold,fontSize=20.sp)}};Spacer(Modifier.width(14.dp));Column(Modifier.weight(1f)){Text(client.name,color=ShahBlack,fontWeight=FontWeight.Bold,fontSize=17.sp);if(client.contactPerson.isNotBlank())Text(client.contactPerson,color=ShahGreen,fontSize=12.sp,fontWeight=FontWeight.Medium)};IconButton(onClick=onMenu){Icon(Icons.Default.MoreVert,"Client payment options")}};Spacer(Modifier.height(8.dp));ClientDetailRow(Icons.Default.Phone,client.phone);ClientDetailRow(Icons.Default.Phone,if(client.whatsapp.isNotBlank())"WhatsApp: ${client.whatsapp}" else "");ClientDetailRow(Icons.Default.Email,client.email);ClientDetailRow(Icons.Default.LocationOn,listOf(client.address,client.city,client.state,client.pincode).filter{it.isNotBlank()}.joinToString(", "));if(!client.gstin.isNullOrBlank())Text("GSTIN: ${client.gstin}",fontSize=11.sp,color=ShahMediumGrey,modifier=Modifier.padding(top=5.dp));if(client.pan.isNotBlank())Text("PAN: ${client.pan}",fontSize=11.sp,color=ShahMediumGrey);if(client.website.isNotBlank())Text("Website: ${client.website}",fontSize=11.sp,color=ShahGreen);if(client.notes.isNotBlank())Text(client.notes,fontSize=11.sp,color=ShahMediumGrey,modifier=Modifier.padding(top=5.dp));HorizontalDivider(Modifier.padding(vertical=10.dp));Row(horizontalArrangement=Arrangement.spacedBy(7.dp),modifier=Modifier.fillMaxWidth()){MoneyBox("TOTAL DUE",client.totalReceivable,Modifier.weight(1f));MoneyBox("RECEIVED",client.totalPaid,Modifier.weight(1f));MoneyBox("PENDING",pending,Modifier.weight(1f))};Text(status,color=when(status){"FULLY PAID"->SuccessGreen;"PARTIAL"->WarningAmber;"PENDING"->ErrorRed;else->ShahMediumGrey},fontWeight=FontWeight.Bold,fontSize=10.sp,modifier=Modifier.padding(top=8.dp))}}}

@Composable private fun MoneyBox(label:String,value:Double,modifier:Modifier){Surface(modifier,RoundedCornerShape(10.dp),color=ShahGrey){Column(Modifier.padding(8.dp)){Text(label,fontSize=8.sp,color=ShahMediumGrey);Text("₹ ${String.format(Locale.ENGLISH,"%,.2f",value)}",fontSize=11.sp,fontWeight=FontWeight.Bold,color=ShahDarkGreen)}}}

@Composable private fun AddReceivableDialog(client:ClientModel,viewModel:ClientViewModel,onDismiss:()->Unit){var amount by remember{mutableStateOf("")};var error by remember{mutableStateOf<String?>(null)};AlertDialog(onDismissRequest={if(!viewModel.isLoading)onDismiss()},title={Text("Add Amount Due")},text={Column(verticalArrangement=Arrangement.spacedBy(8.dp)){Text("Client: ${client.name}");Text("Current due: ₹ ${String.format(Locale.ENGLISH,"%,.2f",client.totalReceivable)}",fontSize=11.sp,color=ShahMediumGrey);OutlinedTextField(amount,{amount=it},label={Text("Additional amount *")},singleLine=true);error?.let{Text(it,color=ErrorRed,fontSize=11.sp)};viewModel.errorMessage?.let{Text(it,color=ErrorRed,fontSize=11.sp)}}},confirmButton={Button(enabled=!viewModel.isLoading,onClick={val v=amount.toDoubleOrNull();if(v==null||v<=0)error="Enter a valid amount" else viewModel.addReceivable(client.id,v,onDismiss)},colors=ButtonDefaults.buttonColors(containerColor=ShahGreen)){Text(if(viewModel.isLoading)"SAVING..." else "ADD DUE")}},dismissButton={TextButton(onClick=onDismiss){Text("CANCEL")}})}

@OptIn(ExperimentalMaterial3Api::class)
@Composable private fun RecordPaymentDialog(client:ClientModel,viewModel:ClientViewModel,onDismiss:()->Unit){var amount by remember{mutableStateOf("")};var date by remember{mutableStateOf(SimpleDateFormat("yyyy-MM-dd",Locale.ENGLISH).format(Date()))};var mode by remember{mutableStateOf("BANK TRANSFER")};var reference by remember{mutableStateOf("")};var remark by remember{mutableStateOf("")};var menu by remember{mutableStateOf(false)};var error by remember{mutableStateOf<String?>(null)};val pending=(client.totalReceivable-client.totalPaid).coerceAtLeast(0.0);AlertDialog(onDismissRequest={if(!viewModel.isLoading)onDismiss()},title={Text("Record Client Payment")},text={Column(verticalArrangement=Arrangement.spacedBy(8.dp)){Text("Client: ${client.name}",fontWeight=FontWeight.Bold);Text("Pending: ₹ ${String.format(Locale.ENGLISH,"%,.2f",pending)}",color=if(pending>0)ErrorRed else SuccessGreen,fontWeight=FontWeight.Bold);OutlinedTextField(amount,{amount=it},label={Text("Payment amount *")},singleLine=true);OutlinedTextField(date,{date=it},label={Text("Payment date (YYYY-MM-DD) *")},singleLine=true);ExposedDropdownMenuBox(expanded=menu,onExpandedChange={menu=!menu}){OutlinedTextField(mode,{},readOnly=true,label={Text("Payment mode")},modifier=Modifier.menuAnchor().fillMaxWidth());ExposedDropdownMenu(expanded=menu,onDismissRequest={menu=false}){listOf("CASH","BANK TRANSFER","UPI","CHEQUE","CARD","OTHER").forEach{DropdownMenuItem(text={Text(it)},onClick={mode=it;menu=false})}}};OutlinedTextField(reference,{reference=it},label={Text("Transaction / Cheque reference")},singleLine=true);OutlinedTextField(remark,{remark=it},label={Text("Remark")},minLines=2);error?.let{Text(it,color=ErrorRed,fontSize=11.sp)};viewModel.errorMessage?.let{Text(it,color=ErrorRed,fontSize=11.sp)}}},confirmButton={Button(enabled=!viewModel.isLoading,onClick={val v=amount.toDoubleOrNull();try{if(v==null||v<=0)error="Enter a valid payment amount" else if(!date.matches(Regex("\\d{4}-\\d{2}-\\d{2}")))error="Date must be YYYY-MM-DD" else {val parsed=SimpleDateFormat("yyyy-MM-dd",Locale.ENGLISH).apply{isLenient=false}.parse(date)!!;viewModel.recordPayment(client,v,Timestamp(parsed),mode,reference,remark,onDismiss)}}catch(_:Exception){error="Invalid payment date"}},colors=ButtonDefaults.buttonColors(containerColor=ShahGreen)){Text(if(viewModel.isLoading)"SAVING..." else "RECORD PAYMENT")}},dismissButton={TextButton(onClick=onDismiss){Text("CANCEL")}})}

@Composable private fun ClientPaymentHistoryDialog(client:ClientModel,viewModel:ClientViewModel,onDismiss:()->Unit){var history by remember{mutableStateOf<List<ClientPaymentRecord>>(emptyList())};var loading by remember{mutableStateOf(true)};LaunchedEffect(client.id){viewModel.getPaymentHistory(client.id){history=it;loading=false}};val pending=(client.totalReceivable-client.totalPaid).coerceAtLeast(0.0);AlertDialog(onDismissRequest=onDismiss,title={Text("Payment History")},text={Column{Text(client.name,fontWeight=FontWeight.Bold);Spacer(Modifier.height(6.dp));Text("Due: ₹ ${String.format(Locale.ENGLISH,"%,.2f",client.totalReceivable)}   Received: ₹ ${String.format(Locale.ENGLISH,"%,.2f",client.totalPaid)}   Pending: ₹ ${String.format(Locale.ENGLISH,"%,.2f",pending)}",fontSize=10.sp,color=ShahDarkGreen);Spacer(Modifier.height(8.dp));if(loading)Box(Modifier.fillMaxWidth().height(120.dp),contentAlignment=Alignment.Center){CircularProgressIndicator()}else if(history.isEmpty())Text("No payment history found")else LazyColumn(Modifier.fillMaxWidth().heightIn(max=480.dp),verticalArrangement=Arrangement.spacedBy(7.dp)){items(history,key={it.id}){p->Card(Modifier.fillMaxWidth(),RoundedCornerShape(10.dp),colors=CardDefaults.cardColors(containerColor=ShahWhite)){Column(Modifier.padding(10.dp)){Text("₹ ${String.format(Locale.ENGLISH,"%,.2f",p.amount)} • ${p.paymentMode}",fontWeight=FontWeight.Bold);Text("Date: ${p.paymentDate?.toDate()?.let{SimpleDateFormat("dd MMM yyyy",Locale.ENGLISH).format(it)}?:"-"}",fontSize=10.sp);if(p.referenceNumber.isNotBlank())Text("Reference: ${p.referenceNumber}",fontSize=10.sp);if(p.remark.isNotBlank())Text("Remark: ${p.remark}",fontSize=10.sp);Text("Recorded by: ${p.recordedByName.ifBlank{"Admin"}}",fontSize=9.sp,color=ShahMediumGrey)}}}}}},confirmButton={TextButton(onClick=onDismiss){Text("CLOSE")}})}

@Composable private fun ClientDetailRow(icon:androidx.compose.ui.graphics.vector.ImageVector,text:String){if(text.isNotBlank())Row(verticalAlignment=Alignment.CenterVertically,modifier=Modifier.padding(vertical=3.dp)){Icon(icon,null,tint=ShahMediumGrey,modifier=Modifier.size(17.dp));Spacer(Modifier.width(9.dp));Text(text,color=ShahMediumGrey,fontSize=12.sp)}}