package com.shahsurveyors.myapplication.models

import com.google.firebase.Timestamp

data class UserProfile(val uid:String="",val name:String="",val email:String="",val role:String="employee",val department:String="SURVEY",val access:String="ATTENDANCE,TASKS,CHAT,LEAVE,EXPENSE,SALARY,ADVANCE,DSR,SURVEY",val approved:Boolean=false,val active:Boolean=true,val createdAt:Timestamp?=null,val updatedAt:Timestamp?=null,val profileImageUrl:String?=null)
data class AttendanceRecord(val id:String="",val uid:String="",val userName:String="",val date:String="",val punchInTime:Timestamp?=null,val punchOutTime:Timestamp?=null,val punchInLat:Double?=null,val punchInLng:Double?=null,val punchOutLat:Double?=null,val punchOutLng:Double?=null,val siteName:String="",val selfieUrl:String?=null,val status:String="PRESENT",val lateMinutes:Int=0,val earlyOutMinutes:Int=0,val workingMinutes:Int=0,val overtimeMinutes:Int=0,val isLate:Boolean=false,val isEarlyOut:Boolean=false,val punchOutMissing:Boolean=false,val leaveRequestId:String="")
data class ProjectModel(val id:String="",val name:String="",val clientName:String="",val description:String="",val siteLocation:String="",val latitude:Double?=null,val longitude:Double?=null,val geofenceRadius:Double=500.0,val startDate:Timestamp?=null,val endDate:Timestamp?=null,val status:String="ACTIVE",val budget:Double=0.0,val managerId:String="")
data class ExpenseRecord(val id:String="",val uid:String="",val userName:String="",val projectId:String="",val projectName:String="",val category:String="",val amount:Double=0.0,val date:Timestamp?=null,val description:String="",val receiptUrl:String?=null,val status:String="PENDING",val paymentStatus:String="UNPAID",val adminRemark:String="",val reviewedByUid:String="",val reviewedByName:String="",val reviewedAt:Timestamp?=null,val paidByUid:String="",val paidAt:Timestamp?=null,val duplicateKey:String="")
data class DSRModel(val id:String="",val uid:String="",val userName:String="",val projectId:String="",val projectName:String="",val date:Timestamp?=null,val manpowerCount:Int=0,val workDone:String="",val equipmentUsed:String="",val remarks:String="",val photoUrls:List<String> = emptyList())
data class EquipmentModel(val id:String="",val name:String="",val modelNumber:String="",val serialNumber:String="",val category:String="",val status:String="AVAILABLE",val assignedToUid:String?=null,val assignedToName:String?=null,val assignedProjectId:String?=null,val assignedProjectName:String?=null,val handoverLocation:String?=null,val handoverAt:Timestamp?=null,val handoverByUid:String?=null,val handoverByName:String?=null,val handoverAccessories:List<String> = emptyList(),val lastReturnAt:Timestamp?=null,val lastReturnByUid:String?=null,val lastReturnByName:String?=null,val lastReturnLocation:String?=null,val returnRemarks:String?=null,val lastMaintenanceDate:Timestamp?=null)
data class EquipmentHandoverRecord(val id:String="",val equipmentId:String="",val equipmentName:String="",val action:String="",val employeeUid:String="",val employeeName:String="",val projectId:String="",val projectName:String="",val location:String="",val accessories:List<String> = emptyList(),val remarks:String="",val actionAt:Timestamp?=null,val actionByUid:String="",val actionByName:String="")
data class TaskModel(val id:String="",val title:String="",val description:String="",val assignedToUid:String="",val assignedToName:String="",val projectId:String="",val projectName:String="",val dueDate:Timestamp?=null,val priority:String="MEDIUM",val status:String="OPEN")
data class ClientModel(val id:String="",val name:String="",val contactPerson:String="",val email:String="",val phone:String="",val whatsapp:String="",val address:String="",val city:String="",val state:String="",val pincode:String="",val gstin:String?=null,val pan:String="",val website:String="",val notes:String="",val totalReceivable:Double=0.0,val totalPaid:Double=0.0)