package com.shahsurveyors.myapplication.ui.marketing

import androidx.compose.foundation.layout.*
import androidx.compose.foundation.lazy.LazyColumn
import androidx.compose.foundation.lazy.items
import androidx.compose.material3.*
import androidx.compose.runtime.*
import androidx.compose.ui.Modifier
import androidx.compose.ui.unit.dp
import com.google.firebase.firestore.FirebaseFirestore

private data class MarketingItem(
    val id:String="", val workingFor:String="", val reelsEdited:Int=0, val reelsShot:Int=0, val videosShot:Int=0,
    val youtubePosts:Int=0, val youtubeImprovement:String="", val youtubeStatus:String="Not Posted",
    val instagramPosts:Int=0, val instagramImprovement:String="", val instagramStatus:String="Not Posted",
    val facebookPosts:Int=0, val facebookImprovement:String="", val facebookStatus:String="Not Posted", val driveLink:String=""
)

@OptIn(ExperimentalMaterial3Api::class)
@Composable
fun MarketingScreen(onBack:()->Unit){
    val db=remember{FirebaseFirestore.getInstance()}; var items by remember{mutableStateOf<List<MarketingItem>>(emptyList())}; var editing by remember{mutableStateOf<MarketingItem?>(null)}
    var workingFor by remember{mutableStateOf("")}; var reelsEdited by remember{mutableStateOf("0")}; var reelsShot by remember{mutableStateOf("0")}; var videosShot by remember{mutableStateOf("0")}
    var youtubePosts by remember{mutableStateOf("0")}; var youtubeImprovement by remember{mutableStateOf("")}; var youtubeStatus by remember{mutableStateOf("Not Posted")}
    var instagramPosts by remember{mutableStateOf("0")}; var instagramImprovement by remember{mutableStateOf("")}; var instagramStatus by remember{mutableStateOf("Not Posted")}
    var facebookPosts by remember{mutableStateOf("0")}; var facebookImprovement by remember{mutableStateOf("")}; var facebookStatus by remember{mutableStateOf("Not Posted")}; var driveLink by remember{mutableStateOf("")}; var error by remember{mutableStateOf<String?>(null)}
    fun load(){db.collection("marketing").get().addOnSuccessListener{s->items=s.documents.map{d->MarketingItem(d.id,d.getString("workingFor")?:d.getString("client")?:(""),(d.getLong("reelsEdited")?:0).toInt(),(d.getLong("reelsShot")?:0).toInt(),(d.getLong("videosShot")?:0).toInt(),(d.getLong("youtubePosts")?:0).toInt(),d.getString("youtubeImprovement")?:"",d.getString("youtubeStatus")?:"Not Posted",(d.getLong("instagramPosts")?:0).toInt(),d.getString("instagramImprovement")?:"",d.getString("instagramStatus")?:"Not Posted",(d.getLong("facebookPosts")?:0).toInt(),d.getString("facebookImprovement")?:"",d.getString("facebookStatus")?:"Not Posted",d.getString("driveLink")?:"")}}.addOnFailureListener{error=it.message?:"Unable to load marketing data"}}
    fun clear(){workingFor="";reelsEdited="0";reelsShot="0";videosShot="0";youtubePosts="0";youtubeImprovement="";youtubeStatus="Not Posted";instagramPosts="0";instagramImprovement="";instagramStatus="Not Posted";facebookPosts="0";facebookImprovement="";facebookStatus="Not Posted";driveLink="";editing=null;error=null}
    fun edit(x:MarketingItem){editing=x;workingFor=x.workingFor;reelsEdited=x.reelsEdited.toString();reelsShot=x.reelsShot.toString();videosShot=x.videosShot.toString();youtubePosts=x.youtubePosts.toString();youtubeImprovement=x.youtubeImprovement;youtubeStatus=x.youtubeStatus;instagramPosts=x.instagramPosts.toString();instagramImprovement=x.instagramImprovement;instagramStatus=x.instagramStatus;facebookPosts=x.facebookPosts.toString();facebookImprovement=x.facebookImprovement;facebookStatus=x.facebookStatus;driveLink=x.driveLink}
    fun save(){if(workingFor.isBlank()){error="Client / work name is required";return};val data=mapOf("workingFor" to workingFor.trim(),"reelsEdited" to (reelsEdited.toIntOrNull()?:0).coerceAtLeast(0),"reelsShot" to (reelsShot.toIntOrNull()?:0).coerceAtLeast(0),"videosShot" to (videosShot.toIntOrNull()?:0).coerceAtLeast(0),"youtubePosts" to (youtubePosts.toIntOrNull()?:0).coerceAtLeast(0),"youtubeImprovement" to youtubeImprovement.trim(),"youtubeStatus" to youtubeStatus,"instagramPosts" to (instagramPosts.toIntOrNull()?:0).coerceAtLeast(0),"instagramImprovement" to instagramImprovement.trim(),"instagramStatus" to instagramStatus,"facebookPosts" to (facebookPosts.toIntOrNull()?:0).coerceAtLeast(0),"facebookImprovement" to facebookImprovement.trim(),"facebookStatus" to facebookStatus,"driveLink" to driveLink.trim(),"updatedAt" to com.google.firebase.firestore.FieldValue.serverTimestamp());val ref=editing?.id?.takeIf{it.isNotBlank()}?.let{db.collection("marketing").document(it)}?:db.collection("marketing").document();ref.set(data).addOnSuccessListener{clear();load()}.addOnFailureListener{error=it.message?:"Save failed"}}
    LaunchedEffect(Unit){load()}
    Scaffold(topBar={TopAppBar(title={Text("Marketing Tracker")},navigationIcon={TextButton(onClick=onBack){Text("Back")}})},floatingActionButton={FloatingActionButton(onClick={::clear}){Text("+")}}){pad->LazyColumn(Modifier.fillMaxSize().padding(pad).padding(16.dp),verticalArrangement=Arrangement.spacedBy(10.dp)){
        item{Text(if(editing==null)"Add Marketing Update" else "Edit Marketing Update",style=MaterialTheme.typography.titleLarge);OutlinedTextField(workingFor,{workingFor=it},Modifier.fillMaxWidth(),label={Text("Working for / Client")});Spacer(Modifier.height(6.dp));Row(horizontalArrangement=Arrangement.spacedBy(8.dp)){OutlinedTextField(reelsEdited,{reelsEdited=it.filter(Char::isDigit)},Modifier.weight(1f),label={Text("Reels Edited")});OutlinedTextField(reelsShot,{reelsShot=it.filter(Char::isDigit)},Modifier.weight(1f),label={Text("Reels Shot")})};OutlinedTextField(videosShot,{videosShot=it.filter(Char::isDigit)},Modifier.fillMaxWidth(),label={Text("Shoot Videos")});Spacer(Modifier.height(8.dp));PlatformBlock("YouTube",youtubePosts,{youtubePosts=it},youtubeStatus,{youtubeStatus=it},youtubeImprovement,{youtubeImprovement=it});PlatformBlock("Instagram",instagramPosts,{instagramPosts=it},instagramStatus,{instagramStatus=it},instagramImprovement,{instagramImprovement=it});PlatformBlock("Facebook",facebookPosts,{facebookPosts=it},facebookStatus,{facebookStatus=it},facebookImprovement,{facebookImprovement=it});OutlinedTextField(driveLink,{driveLink=it},Modifier.fillMaxWidth(),label={Text("Google Drive Link")});Row(horizontalArrangement=Arrangement.spacedBy(8.dp)){Button(onClick=::save,Modifier.weight(1f)){Text(if(editing==null)"SAVE" else "UPDATE")};if(editing!=null)OutlinedButton(onClick=::clear,Modifier.weight(1f)){Text("CANCEL")}};error?.let{Text(it,color=MaterialTheme.colorScheme.error)};Text("Marketing History",style=MaterialTheme.typography.titleMedium)}
        items(items){x->Card(Modifier.fillMaxWidth()){Column(Modifier.padding(14.dp),verticalArrangement=Arrangement.spacedBy(3.dp)){Text(x.workingFor,style=MaterialTheme.typography.titleMedium);Text("Reels: ${x.reelsEdited} edited • ${x.reelsShot} shot • Videos: ${x.videosShot} shot");Text("YouTube: ${x.youtubePosts} posts • ${x.youtubeStatus}");Text("Instagram: ${x.instagramPosts} posts • ${x.instagramStatus}");Text("Facebook: ${x.facebookPosts} posts • ${x.facebookStatus}");if(x.youtubeImprovement.isNotBlank())Text("YouTube improvement: ${x.youtubeImprovement}");if(x.instagramImprovement.isNotBlank())Text("Instagram improvement: ${x.instagramImprovement}");if(x.facebookImprovement.isNotBlank())Text("Facebook improvement: ${x.facebookImprovement}");if(x.driveLink.isNotBlank())Text("Drive: ${x.driveLink}");Row{OutlinedButton(onClick={edit(x)}){Text("EDIT")};TextButton(onClick={db.collection("marketing").document(x.id).delete().addOnSuccessListener{load()}.addOnFailureListener{error=it.message}}){Text("DELETE")}}}}}
    }}
}

@Composable
private fun PlatformBlock(name:String,posts:String,onPosts:(String)->Unit,status:String,onStatus:(String)->Unit,improvement:String,onImprovement:(String)->Unit){Column(verticalArrangement=Arrangement.spacedBy(5.dp)){Text(name,style=MaterialTheme.typography.titleMedium);Row(horizontalArrangement=Arrangement.spacedBy(8.dp)){OutlinedTextField(posts,{onPosts(it.filter(Char::isDigit))},Modifier.weight(1f),label={Text("Posts")});OutlinedTextField(status,onStatus,Modifier.weight(1f),label={Text("Status")})};OutlinedTextField(improvement,onImprovement,Modifier.fillMaxWidth(),label={Text("Improvement / Update")})}}
