package com.shahsurveyors.myapplication.ui.equipment

import androidx.compose.foundation.background
import androidx.compose.foundation.layout.*
import androidx.compose.foundation.lazy.LazyColumn
import androidx.compose.foundation.lazy.items
import androidx.compose.foundation.shape.RoundedCornerShape
import androidx.compose.material.icons.Icons
import androidx.compose.material.icons.automirrored.filled.ArrowBack
import androidx.compose.material.icons.filled.*
import androidx.compose.material3.*
import androidx.compose.runtime.*
import androidx.compose.ui.Alignment
import androidx.compose.ui.Modifier
import androidx.compose.ui.graphics.Color
import androidx.compose.ui.text.font.FontWeight
import androidx.compose.ui.unit.dp
import androidx.compose.ui.unit.sp
import com.shahsurveyors.myapplication.models.*
import com.shahsurveyors.myapplication.ui.theme.*
import java.text.SimpleDateFormat
import java.util.Locale

@OptIn(ExperimentalMaterial3Api::class)
@Composable
fun EquipmentTrackerScreen(viewModel: EquipmentViewModel, onBack: () -> Unit = {}) {
    var showAddDialog by remember { mutableStateOf(false) }; var handoverItem by remember { mutableStateOf<EquipmentModel?>(null) }; var historyItem by remember { mutableStateOf<EquipmentModel?>(null) }
    LaunchedEffect(Unit){viewModel.fetchEquipment()}
    val total=viewModel.equipmentList.size; val available=viewModel.equipmentList.count{it.status=="AVAILABLE"}; val inUse=viewModel.equipmentList.count{it.status=="IN_USE"}
    Scaffold(topBar={TopAppBar(title={Column{Text("Leica Fleet Custody",fontWeight=FontWeight.Bold,color=ShahWhite);Text("Equipment & handover tracking",fontSize=10.sp,color=ShahWhite.copy(.72f))}},navigationIcon={IconButton(onClick=onBack){Icon(Icons.AutoMirrored.Filled.ArrowBack,"Back",tint=ShahWhite)}},colors=TopAppBarDefaults.topAppBarColors(containerColor=ShahDarkGreen))},floatingActionButton={FloatingActionButton(onClick={showAddDialog=true},containerColor=ShahGreen,contentColor=ShahWhite,shape=RoundedCornerShape(16.dp)){Icon(Icons.Default.Add,"Add Equipment")}}){padding->Column(Modifier.padding(padding).fillMaxSize().background(ShahGrey)){Row(Modifier.fillMaxWidth().padding(16.dp),horizontalArrangement=Arrangement.spacedBy(10.dp)){EquipmentSummary("Total",total.toString(),Icons.Default.Inventory2,ShahGreen,Modifier.weight(1f));EquipmentSummary("Available",available.toString(),Icons.Default.CheckCircle,SuccessGreen,Modifier.weight(1f));EquipmentSummary("In Use",inUse.toString(),Icons.Default.PersonPin,WarningAmber,Modifier.weight(1f))};if(viewModel.equipmentList.isEmpty()&&!viewModel.isLoading)Box(Modifier.fillMaxSize(),contentAlignment=Alignment.Center){Text("No equipment found") }else LazyColumn(Modifier.fillMaxSize(),contentPadding=PaddingValues(16.dp),verticalArrangement=Arrangement.spacedBy(10.dp)){items(viewModel.equipmentList,key={it.id}){EquipmentCard(it,onHandover={handoverItem=it},onReturn={handoverItem=it},onHistory={historyItem=it})}}}}
    if(showAddDialog)AddEquipmentDialog(viewModel){showAddDialog=false};handoverItem?.let{item->if(item.status=="IN_USE")ReturnDialog(item,viewModel){handoverItem=null}else HandoverDialog(item,viewModel){handoverItem=null}};historyItem?.let{item->HistoryDialog(item,viewModel){historyItem=null}}
}

@Composable private fun AddEquipmentDialog(viewModel:EquipmentViewModel,onDismiss:()->Unit){var name by remember{mutableStateOf("")};var model by remember{mutableStateOf("")};var serial by remember{mutableStateOf("")};var category by remember{mutableStateOf("Survey Instrument")};AlertDialog(onDismissRequest=onDismiss,title={Text("Add Equipment",fontWeight=FontWeight.Bold)},text={Column(verticalArrangement=Arrangement.spacedBy(8.dp)){OutlinedTextField(name,{name=it},label={Text("Equipment name *")},singleLine=true);OutlinedTextField(model,{model=it},label={Text("Model number")},singleLine=true);OutlinedTextField(serial,{serial=it},label={Text("Serial number *")},singleLine=true);OutlinedTextField(category,{category=it},label={Text("Category")},singleLine=true)}},confirmButton={Button(enabled=name.isNotBlank()&&serial.isNotBlank()&&!viewModel.isLoading,onClick={viewModel.addEquipment(name,model,serial,category,onDismiss)},colors=ButtonDefaults.buttonColors(containerColor=ShahGreen)){Text("SAVE")}},dismissButton={TextButton(onClick=onDismiss){Text("CANCEL")}})}

@OptIn(ExperimentalMaterial3Api::class)
@Composable private fun HandoverDialog(item:EquipmentModel,viewModel:EquipmentViewModel,onDismiss:()->Unit){var employee by remember{mutableStateOf<UserProfile?>(null)};var project by remember{mutableStateOf<ProjectModel?>(null)};var location by remember{mutableStateOf("")};var other by remember{mutableStateOf("")};var ee by remember{mutableStateOf(false)};var pe by remember{mutableStateOf(false)};val checks=remember{mutableStateMapOf("Tripod" to false,"Prism" to false,"Battery x2" to false,"Charger" to false,"Tribrach" to false)};LaunchedEffect(Unit){viewModel.clearError();viewModel.loadHandoverOptions()};val accessories=checks.filterValues{it}.keys.toMutableList().apply{addAll(other.split(',').map{it.trim()}.filter{it.isNotBlank()})}.distinct();AlertDialog(onDismissRequest={if(!viewModel.isLoading)onDismiss()},title={Text("Confirm Equipment Handover")},text={Column(verticalArrangement=Arrangement.spacedBy(7.dp)){ExposedDropdownMenuBox(ee,{ee=!ee}){OutlinedTextField(employee?.name.orEmpty(),{},readOnly=true,label={Text("Handover to *")},modifier=Modifier.menuAnchor().fillMaxWidth());ExposedDropdownMenu(ee,{ee=false}){if(viewModel.employees.isEmpty())DropdownMenuItem(text={Text("No active employees found")},onClick={})else viewModel.employees.forEach{u->DropdownMenuItem(text={Text(u.name)},onClick={employee=u;ee=false})}}};ExposedDropdownMenuBox(pe,{pe=!pe}){OutlinedTextField(project?.name.orEmpty(),{},readOnly=true,label={Text("Project *")},modifier=Modifier.menuAnchor().fillMaxWidth());ExposedDropdownMenu(pe,{pe=false}){if(viewModel.projects.isEmpty())DropdownMenuItem(text={Text("No active projects found")},onClick={})else viewModel.projects.forEach{p->DropdownMenuItem(text={Text(p.name)},onClick={project=p;pe=false})}}};OutlinedTextField(location,{location=it},label={Text("Handover location *")},singleLine=true);Text("Accessories",fontWeight=FontWeight.Bold,color=ShahGreen);checks.keys.forEach{a->Row(verticalAlignment=Alignment.CenterVertically){Checkbox(checks[a]==true,{checks[a]=it});Text(a,fontSize=11.sp)}};OutlinedTextField(other,{other=it},label={Text("Other accessories")},minLines=2)}},confirmButton={Button(enabled=employee!=null&&project!=null&&location.isNotBlank()&&!viewModel.isLoading,onClick={viewModel.handoverEquipment(item.id,employee!!,project!!,location,accessories,onDismiss)},colors=ButtonDefaults.buttonColors(containerColor=ShahGreen)){Text("CONFIRM HANDOVER")}},dismissButton={TextButton(onClick=onDismiss){Text("CANCEL")}})}

@Composable private fun ReturnDialog(item:EquipmentModel,viewModel:EquipmentViewModel,onDismiss:()->Unit){var location by remember{mutableStateOf("")};var remarks by remember{mutableStateOf("")};AlertDialog(onDismissRequest={if(!viewModel.isLoading)onDismiss()},title={Text("Return Equipment")},text={Column(verticalArrangement=Arrangement.spacedBy(8.dp)){Text("Return from: ${item.assignedToName.orEmpty()}");Text("Project: ${item.assignedProjectName.orEmpty()}");OutlinedTextField(location,{location=it},label={Text("Return location *")},singleLine=true);OutlinedTextField(remarks,{remarks=it},label={Text("Condition / remarks")},minLines=2)}},confirmButton={Button(enabled=location.isNotBlank()&&!viewModel.isLoading,onClick={viewModel.returnEquipment(item.id,location,remarks);onDismiss()},colors=ButtonDefaults.buttonColors(containerColor=ShahGreen)){Text("CONFIRM RETURN")}},dismissButton={TextButton(onClick=onDismiss){Text("CANCEL")}})}

@Composable private fun HistoryDialog(item:EquipmentModel,viewModel:EquipmentViewModel,onDismiss:()->Unit){var history by remember{mutableStateOf<List<EquipmentHandoverRecord>>(emptyList())};var loading by remember{mutableStateOf(true)};LaunchedEffect(item.id){loading=true;viewModel.getHistory(item.id){result->history=result;loading=false}};AlertDialog(onDismissRequest=onDismiss,title={Text("Handover History")},text={if(loading)CircularProgressIndicator()else if(history.isEmpty())Text("No history found")else Column{history.take(20).forEach{h->Text("${h.action} • ${h.employeeName}",fontWeight=FontWeight.Bold);Text("${h.projectName} • ${h.location}",fontSize=10.sp);Text(h.actionAt?.toDate()?.let{SimpleDateFormat("dd MMM yyyy, hh:mm a",Locale.ENGLISH).format(it)} ?: "",fontSize=9.sp,color=ShahMediumGrey);if(h.accessories.isNotEmpty())Text("Accessories: ${h.accessories.joinToString()}",fontSize=9.sp);if(h.remarks.isNotBlank())Text("Remarks: ${h.remarks}",fontSize=9.sp);HorizontalDivider(Modifier.padding(vertical=6.dp))}}},confirmButton={TextButton(onClick=onDismiss){Text("CLOSE")}})}

@Composable private fun EquipmentSummary(title:String,value:String,icon:androidx.compose.ui.graphics.vector.ImageVector,tint:Color,modifier:Modifier){Card(modifier,RoundedCornerShape(14.dp),colors=CardDefaults.cardColors(containerColor=ShahWhite)){Column(Modifier.padding(10.dp)){Icon(icon,null,tint=tint,modifier=Modifier.size(19.dp));Text(value,fontWeight=FontWeight.Bold,fontSize=17.sp);Text(title,fontSize=9.sp,color=ShahMediumGrey)}}}

@Composable private fun EquipmentCard(item:EquipmentModel,onHandover:()->Unit,onReturn:()->Unit,onHistory:()->Unit){var expanded by remember{mutableStateOf(false)};val c=when(item.status){"AVAILABLE"->SuccessGreen;"IN_USE"->WarningAmber;"MAINTENANCE"->ErrorRed;else->ShahMediumGrey};Card(Modifier.fillMaxWidth(),RoundedCornerShape(16.dp),colors=CardDefaults.cardColors(containerColor=ShahWhite)){Column(Modifier.padding(15.dp)){Row(verticalAlignment=Alignment.CenterVertically){Column(Modifier.weight(1f)){Text(item.name,fontWeight=FontWeight.Bold);Text("S/N: ${item.serialNumber}",fontSize=10.sp,color=ShahMediumGrey);Surface(shape=RoundedCornerShape(8.dp),color=c.copy(.10f)){Text(item.status,color=c,fontSize=9.sp,fontWeight=FontWeight.Bold,modifier=Modifier.padding(6.dp))};item.assignedToName?.takeIf{it.isNotBlank()}?.let{Text("Assigned: $it",fontSize=10.sp)};item.assignedProjectName?.takeIf{it.isNotBlank()}?.let{Text("Project: $it",fontSize=10.sp)}};IconButton(onClick={expanded=!expanded}){Icon(if(expanded)Icons.Default.ExpandLess else Icons.Default.ExpandMore,null)}};if(expanded){HorizontalDivider();item.handoverLocation?.let{Text("Location: $it",fontSize=10.sp)};item.handoverAt?.let{Text("Handover: ${it.toDate()}",fontSize=10.sp)};if(item.handoverAccessories.isNotEmpty())Text("Accessories: ${item.handoverAccessories.joinToString()}",fontSize=10.sp);if(item.lastReturnLocation?.isNotBlank()==true)Text("Last return: ${item.lastReturnLocation}",fontSize=10.sp);Row(Modifier.fillMaxWidth().padding(top=8.dp),horizontalArrangement=Arrangement.spacedBy(6.dp)){if(item.status=="AVAILABLE")Button(onClick=onHandover,Modifier.weight(1f)){Text("HANDOVER")};if(item.status=="IN_USE")OutlinedButton(onClick=onReturn,Modifier.weight(1f)){Text("RETURN")};OutlinedButton(onClick=onHistory,Modifier.weight(1f)){Text("HISTORY")}}}}}}
